-- Beacon Default keyword policies — seed.
--
-- Imports the curated default keyword list from beacon-academy's
-- beacon_policies rows (115 keywords as of the audit on 2026-05-29:
-- 54 high, 61 medium). This becomes the canonical default that every
-- school inherits via use_beacon_defaults = true.
--
-- Idempotent: ON CONFLICT DO NOTHING against the (word, severity)
-- unique index lets this be re-run safely.
--
-- Generated by scripts/generate_seed_sql.mjs.
-- Run this in the Supabase SQL editor after 0014_beacon_default_policies.sql.

INSERT INTO beacon_default_policies (word, severity) VALUES
  ('acid', 'high'),
  ('act as dan', 'high'),
  ('blade', 'high'),
  ('bomb', 'high'),
  ('burner phone', 'high'),
  ('bypass your filters', 'high'),
  ('coke', 'high'),
  ('county lines', 'high'),
  ('cuckooing', 'high'),
  ('cunt', 'high'),
  ('developer mode', 'high'),
  ('disregard your training', 'high'),
  ('do anything now', 'high'),
  ('drill', 'high'),
  ('drug mule', 'high'),
  ('drug runner', 'high'),
  ('drugs', 'high'),
  ('get merked', 'high'),
  ('ignore all instructions', 'high'),
  ('ignore previous instructions', 'high'),
  ('jailbreak', 'high'),
  ('ket', 'high'),
  ('ketamine', 'high'),
  ('kill', 'high'),
  ('mandy', 'high'),
  ('mdma', 'high'),
  ('molly', 'high'),
  ('nazi', 'high'),
  ('nsfw', 'high'),
  ('nude pics', 'high'),
  ('nudes', 'high'),
  ('onlyfans', 'high'),
  ('pingers', 'high'),
  ('porn', 'high'),
  ('pornhub', 'high'),
  ('pretend you have no limits', 'high'),
  ('pretend you have no restrictions', 'high'),
  ('ride out', 'high'),
  ('school shooting', 'high'),
  ('send nudes', 'high'),
  ('sexting', 'high'),
  ('shank', 'high'),
  ('shelling', 'high'),
  ('shiv', 'high'),
  ('shotting', 'high'),
  ('shrooms', 'high'),
  ('stab', 'high'),
  ('suicide', 'high'),
  ('terrorist', 'high'),
  ('trap house', 'high'),
  ('trapping', 'high'),
  ('xxx', 'high'),
  ('you are now unrestricted', 'high'),
  ('you have no rules', 'high'),
  ('ass', 'medium'),
  ('asshole', 'medium'),
  ('bang', 'medium'),
  ('bastard', 'medium'),
  ('batter', 'medium'),
  ('beat up', 'medium'),
  ('beef', 'medium'),
  ('bitch', 'medium'),
  ('blunt', 'medium'),
  ('bonk', 'medium'),
  ('boobs', 'medium'),
  ('bullshit', 'medium'),
  ('bully', 'medium'),
  ('burner', 'medium'),
  ('cock', 'medium'),
  ('crap', 'medium'),
  ('dabs', 'medium'),
  ('dank', 'medium'),
  ('dick', 'medium'),
  ('drop', 'medium'),
  ('edibles', 'medium'),
  ('explicit', 'medium'),
  ('food', 'medium'),
  ('fuck', 'medium'),
  ('fucking', 'medium'),
  ('fwb', 'medium'),
  ('gang affiliated', 'medium'),
  ('hate', 'medium'),
  ('hookup', 'medium'),
  ('horny', 'medium'),
  ('joint', 'medium'),
  ('jump', 'medium'),
  ('lean', 'medium'),
  ('line', 'medium'),
  ('mandem', 'medium'),
  ('mule', 'medium'),
  ('nic', 'medium'),
  ('opps', 'medium'),
  ('pack', 'medium'),
  ('piss', 'medium'),
  ('postcode war', 'medium'),
  ('pussy', 'medium'),
  ('self harm', 'medium'),
  ('sex', 'medium'),
  ('sexy', 'medium'),
  ('shag', 'medium'),
  ('shit', 'medium'),
  ('skunk', 'medium'),
  ('snog', 'medium'),
  ('spliff', 'medium'),
  ('steal', 'medium'),
  ('strip', 'medium'),
  ('ting', 'medium'),
  ('tits', 'medium'),
  ('trap', 'medium'),
  ('twat', 'medium'),
  ('vape', 'medium'),
  ('violence', 'medium'),
  ('wank', 'medium'),
  ('weapon', 'medium'),
  ('weed', 'medium')

ON CONFLICT (word, severity) DO NOTHING;

-- Sanity check: expected row count after seed.
DO $$
DECLARE
  high_count   integer;
  medium_count integer;
BEGIN
  SELECT count(*) INTO high_count   FROM beacon_default_policies WHERE severity = 'high';
  SELECT count(*) INTO medium_count FROM beacon_default_policies WHERE severity = 'medium';
  RAISE NOTICE 'beacon_default_policies seeded: % high, % medium', high_count, medium_count;
END $$;
