// Generate INSERT statements for 0015_seed_beacon_defaults.sql by reading
// beacon-academy's 115 policies from the live DB. Output goes to stdout.
//
// Run: node scripts/generate_seed_sql.mjs > supabase/sql/0015_seed_beacon_defaults.sql

import { readFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";

const env = Object.fromEntries(
  readFileSync(".env.local", "utf8")
    .split(/\r?\n/)
    .filter(l => l && !l.startsWith("#") && l.includes("="))
    .map(l => {
      const i = l.indexOf("=");
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
    })
);

const supabase = createClient(
  env.NEXT_PUBLIC_SUPABASE_URL,
  env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
);

const { data: rows, error } = await supabase
  .from("beacon_policies")
  .select("word,severity")
  .eq("school_id", "beacon-academy")
  .order("severity")
  .order("word");

if (error) {
  console.error("-- Query failed:", error.message);
  process.exit(1);
}

// Postgres single-quote escaping: ' -> ''
const esc = s => s.replace(/'/g, "''");

const header = `-- Beacon Default keyword policies — seed.
--
-- Imports the curated default keyword list from beacon-academy's
-- beacon_policies rows (115 keywords as of the audit on 2026-05-29:
-- 54 high, 61 medium). This becomes the canonical default that every
-- school inherits via use_beacon_defaults = true.
--
-- Idempotent: ON CONFLICT DO NOTHING against the (word, severity)
-- unique index lets this be re-run safely.
--
-- Generated by scripts/generate_seed_sql.mjs.
-- Run this in the Supabase SQL editor after 0014_beacon_default_policies.sql.

INSERT INTO beacon_default_policies (word, severity) VALUES`;

const values = rows
  .map(r => `  ('${esc(r.word)}', '${r.severity}')`)
  .join(",\n");

const footer = `\nON CONFLICT (word, severity) DO NOTHING;

-- Sanity check: expected row count after seed.
DO $$
DECLARE
  high_count   integer;
  medium_count integer;
BEGIN
  SELECT count(*) INTO high_count   FROM beacon_default_policies WHERE severity = 'high';
  SELECT count(*) INTO medium_count FROM beacon_default_policies WHERE severity = 'medium';
  RAISE NOTICE 'beacon_default_policies seeded: % high, % medium', high_count, medium_count;
END $$;`;

console.log(header);
console.log(values);
console.log(footer);
